### ISSUE TITLE
cannot find module

### ISSUE THREAD

**Issue by Refluent1** [stuyy/djs-v14-tutorial#1]
Error: Cannot find module '/home/runner/bot/index.js'
Require stack:
- /nix/store/29fdcv1yhlll61ml8a31qdkrbprxd7gs-prybar-nodejs-0.0.0-67f7a00/prybar_assets/nodejs/module-context-hook.js
- /tmp/prybar-nodejs-2197728537.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:956:15)
    at Function.resolve (node:internal/modules/cjs/helpers:108:19)

Can anyone please help? I'm new to coding.

**Comment by ghost** [comment]
Its not an error with the code,
Its because you are trying to run a file that doesn't exist.

**Comment by EmeraldGltch** [comment]
> Its not an error with the code, Its because you are trying to run a file that doesn't exist.

when you set up the start:dev script, set the file path to ./src/index.js
This should work if you structure your files properly.
